version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/finance
    command: "npm run dev"

  mongodb:
    image: mongo:latest
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-config:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: finance
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]

volumes:
  mongo-data:
